### ISSUE TITLE
Python error on load 

### ISSUE THREAD

**Issue by CrabbyPete** [nksan/Rpi-SetWiFi-viaBluetooth#5]
I got the following from journalctl 
Aug 21 13:01:20 raspberry python3[321]: Traceback (most recent call last):
Aug 21 13:01:20 raspberry python3[321]:   File "/usr/lib/python3/dist-packages/dbus/bus.py", line 173, in activate_name_owner
Aug 21 13:01:20 raspberry python3[321]:     return self.get_name_owner(bus_name)
Aug 21 13:01:20 raspberry python3[321]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 21 13:01:20 raspberry python3[321]:   File "/usr/lib/python3/dist-packages/dbus/bus.py", line 348, in get_name_owner
Aug 21 13:01:20 raspberry python3[321]:     return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
Aug 21 13:01:20 raspberry python3[321]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 21 13:01:20 raspberry python3[321]:   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 634, in call_blocking
Aug 21 13:01:20 raspberry python3[321]:     reply_message = self.send_message_with_reply_and_block(
Aug 21 13:01:20 raspberry python3[321]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 21 13:01:20 raspberry python3[321]: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.bluez': >
Aug 21 13:01:20 raspberry python3[321]: During handling of the above exception, another exception occurred:
Aug 21 13:01:20 raspberry python3[321]: Traceback (most recent call last):
Aug 21 13:01:20 raspberry python3[321]:   File "/usr/local/btwifiset/btwifiset.py", line 2922, in <module>
Aug 21 13:01:20 raspberry python3[321]:     blemgr.start()
Aug 21 13:01:20 raspberry python3[321]:   File "/usr/local/btwifiset/btwifiset.py", line 2865, in start
Aug 21 13:01:20 raspberry python3[321]:     Blue.set_adapter()
Aug 21 13:01:20 raspberry python3[321]:   File "/usr/local/btwifiset/btwifiset.py", line 2042, in set_adapter
Aug 21 13:01:20 raspberry python3[321]:     obj = Blue.bus.get_object('org.bluez','/')
Aug 21 13:01:20 raspberry python3[321]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 21 13:01:20 raspberry python3[321]:   File "/usr/lib/python3/dist-packages/dbus/bus.py", line 237, in get_object
Aug 21 13:01:20 raspberry python3[321]:     return self.ProxyObjectClass(self, bus_name, object_path,
Aug 21 13:01:20 raspberry python3[321]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 21 13:01:20 raspberry python3[321]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
Aug 21 13:01:20 raspberry python3[321]:     self._named_service = conn.activate_name_owner(bus_name)
Aug 21 13:01:20 raspberry python3[321]:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 21 13:01:20 raspberry python3[321]:   File "/usr/lib/python3/dist-packages/dbus/bus.py", line 178, in activate_name_owner
Aug 21 13:01:20 raspberry python3[321]:     self.start_service_by_name(bus_name)
Aug 21 13:01:20 raspberry python3[321]:   File "/usr/lib/python3/dist-packages/dbus/bus.py", line 273, in start_service_by_name
Aug 21 13:01:20 raspberry python3[321]:     return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
Aug 21 13:01:20 raspberry python3[321]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 21 13:01:20 raspberry python3[321]:   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 634, in call_blocking
Aug 21 13:01:21 raspberry python3[321]:     reply_message = self.send_message_with_reply_and_block(
Aug 21 13:01:21 raspberry python3[321]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 21 13:01:21 raspberry python3[321]: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed o>
Aug 21 13:01:22 raspberry systemd[1]: btwifiset.service: Main process exited, code=exited, status=1/FAILURE
Aug 21 13:01:22 raspberry systemd[1]: btwifiset.service: Failed with result 'exit-code'.
Aug 21 13:01:22 raspberry systemd[1]: btwifiset.service: Consumed 3.794s CPU time.

**Comment by NormFrenette** [comment]
Something is wrong in your install of the OS:
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.bluez'

If dbus can't start - the python code will exit. (which it did).

Can you share what OS/version, what RPI, what Python version you are on?
Also - this maybe obvious but did the install script print out any error messages?
(You can always run it again - it won't hurt anything)

This might be useful:
https://askubuntu.com/questions/1456955/org-freedesktop-dbus-error-namehasnoowner-could-not-get-owner-of-name-org-debi
it suggest you run:
sudo systemctl status dbus
and see what error messages you get.

I know enough to use dbus to communicate with blueZ - but i'm not really an expert in understanding why blueZ would not work...

**Comment by CrabbyPete** [comment]
I was using bookworm on a Raspberry Pi Zero.  Other than this I got no error messages. I will check all these shortly. Thanks for the support
